[package]
name = "style_system"
version = "0.1.0"
edition = "2021"

[dependencies]
cssparser = "0.29.6"
parcel_selectors = { version = "0.24.2", path = "./selectors" }
morphorm = {git = "https://github.com/vizia/morphorm", features = ["rounding"], rev = "c14e888b1d66719fc3f13ccdb1ea01a10368ef9e" }
